# Generated by Django 5.2 on 2025-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
