# Generated by Django 5.1.6 on 2025-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_variant_orderitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
