# Generated by Django 5.1.6 on 2025-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_scheduled_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Fully Paid', 'Fully Paid'), ('Cancelled', 'Cancelled'), ('Assigned', 'Assigned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
