# Generated by Django 5.1.6 on 2025-04-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remaining_payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fully Paid', 'Fully Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
