# Generated by Django 5.1.6 on 2025-04-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_email_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fully Paid', 'Fully Paid'), ('On Delivery', 'On Delivery')], default='Pending', max_length=20),
        ),
    ]
