# Generated by Django 5.1.6 on 2025-04-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
