# Generated by Django 5.1.6 on 2025-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_need_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='need_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
