# Generated by Django 5.2 on 2025-04-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_need_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting', 'Waiting'), ('Fully Paid', 'Fully Paid'), ('Cancelled', 'Cancelled'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Ignored', 'Ignored'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
