# Generated by Django 5.2 on 2025-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_customer_latitude_order_customer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('Fully Paid', 'Fully Paid'), ('Cancelled', 'Cancelled'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('Ignored', 'Ignored'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
